### ISSUE TITLE
Hardware spec

### ISSUE THREAD

**Issue by Zacchaeus14** [michaelnny/alpha_zero#1]
Great work. May I ask what is your GPU specification to train the model and how long did it take to converge?

**Comment by michaelnny** [comment]
Hi, thanks for your interests in the project. I've update the README.md file to include the details.

We tried to run the training on both M1 Mac Mini and Ubuntu linux with a single RTX 2080 Ti GPU.
It took 3 days to reach 500k training steps which is a reasonable strong player but not the best.

We set the train_delay parameters to a certain value so that it takes about 10 minutes to run 1k training steps and generate one new checkpoint, we didn't count exactly how many games were played by the actors. 

Maybe we can still fine tune it, but we're pretty satisfied with the result and we don't want to wast another few days to re-run the whole experiments.
