### ISSUE TITLE
Model performance

### ISSUE THREAD

**Issue by yfismine** [michaelnny/alpha_zero#2]
Why your pre-trained model seems to be in a random drop on my computer
![image](https://user-images.githubusercontent.com/53209596/176083698-66dcb2b5-2543-4b67-83d8-6c3615086ced.png)

**Comment by michaelnny** [comment]
This is expected as noted in the README.md, the agent failed to do well on 'edge' case. The reason is because we only trained the agent for 500k steps. We suspect the self-play couldn't reach the edges since most of the game will end around 40-50 steps at the early stage of training.

There's another possible issue is the model capacity too small. If you really want a strong agent, you can try to increase the number of planes and res-blocks in the model, and train it longer like 5-10 million steps.

**Comment by yfismine** [comment]
![image](https://user-images.githubusercontent.com/53209596/176085314-29c00983-2d57-4039-8291-fc7fea41250f.png)

**Comment by yfismine** [comment]
Your model doesn't seem to be defensive, or maybe there's something wrong with my running mode.

**Comment by yfismine** [comment]
It's okay, because I submitted a similar project yesterday. It's a 15*15 Gomoku model, and its ability is quite good. I just want to see how other people's models perform.

**Comment by michaelnny** [comment]
I just run the code it works on my computer and it can still beat me. But not sure maybe the GUI program has some bug or something which is hard to tell. 

Also we only trained the model for 500k steps, and use a much smaller model, so it's definitely not the strongest player.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/56952187/176086478-9c3add18-08cf-4080-bcb7-87950bd9bfb1.png">
